### PR TITLE
Add alt text to anchors on email-x advertisements.

### PR DESCRIPTION
**Pull request by Shinsina**
Screen Shot 2021-06-07 at 12 08 37 PM
Depends on https://github.com/parameter1/base-cms/pull/96

### CODE REVIEW

**Comment by Shinsina** [comment]
[Add option for alt text on Email-X banner ads](https://trello.com/c/gcxrc7RQ/11-add-option-for-alt-text-on-email-x-banner-ads)

**Review by brandonbk — CHANGES_REQUESTED** [review]
@Shinsina - the alt property should be on the `` tag, not the anchor.

**Comment by Shinsina** [comment]
https://github.com/parameter1/base-cms/pull/96#issuecomment-856163967

**Comment by solocommand** [comment]
> @Shinsina - the alt property should be on the `` tag, not the anchor.

It should also be part of the `imageAttrs` object, not included separately. Looks like there a conflict here that needs to be resolved to continue.

**Pull request closed without merging**
