### PR TITLE
[DPP-4706] Updated WellSpa 360 Newsletter Header images

### PR DESCRIPTION
**Pull request by afrederick**
to include the 'formerly Dayspa' tag. Images are already uploaded to P1 S3.

WellSpa360-Newsletter-Headers

### CODE REVIEW

**Comment by afrederick** [comment]
@brandonbk / @solocommand - Can we get this merged and pushed live so the Editor's can create tomorrow's newsletters with the updated logo? Thank you!

**Review by solocommand — APPROVED** [review]
Sorry @afrederick, didn't see this one come through! Will get this merged and deployed ASAP.

**Comment by solocommand** [comment]
@afrederick sorry for the delay -- these changes are now live.

**Comment by afrederick** [comment]
@solocommand - Thank you. I forgot to add a mention to the original PR, so I apologize.

**Pull request merged**
